# coding=utf-8
from typing import Hashable, Tuple, TypeVar

NOMINAL_INPUT = Hashable
NOMINAL_OUTPUT = Hashable

NOMINAL_SENSOR = Hashable
NOMINAL_MOTOR = Hashable

RATIONAL_INPUT = Tuple[float, ...]
RATIONAL_OUTPUT = Tuple[float, ...]

RATIONAL_SENSOR = Tuple[float, ...]
RATIONAL_MOTOR = Tuple[float, ...]

PREDICTOR_STATE = Tuple[Tuple[int, ...], ...]

TYPE_A = TypeVar("TYPE_A")

HISTORY = Tuple[TYPE_A, ...]


INPUT_TYPE = TypeVar("INPUT_TYPE")
OUTPUT_TYPE = TypeVar("OUTPUT_TYPE")

EXAMPLE = Tuple[INPUT_TYPE, OUTPUT_TYPE]


MOTOR_TYPE = TypeVar("MOTOR_TYPE")
SENSOR_TYPE = TypeVar("SENSOR_TYPE")

SENSORIMOTOR_INPUT = Tuple[SENSOR_TYPE, MOTOR_TYPE]
SENSORIMOTOR_HISTORY = HISTORY[SENSORIMOTOR_INPUT]
SENSORIMOTOR_EXAMPLE = EXAMPLE[SENSORIMOTOR_HISTORY, SENSOR_TYPE]
CONTROLLER_PERCEPTION = Tuple[SENSORIMOTOR_HISTORY, PREDICTOR_STATE]

